version: '3.8'
services:

## --------------------------- POSTGRESQL --------------------------- ##

  postgres:
    image: postgres:15-alpine
    container_name: disparador_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=disparador_db
      - POSTGRES_USER=disparador_user
      - POSTGRES_PASSWORD=disparador_pass_2025
      - TZ=America/Sao_Paulo
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - disparador_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U disparador_user -d disparador_db"]
      interval: 10s
      timeout: 5s
      retries: 5

## --------------------------- DISPARADOR --------------------------- ##

  disparador:
    image: oriondesign/disparador:latest
    container_name: disparador
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - disparador_data:/app/public/uploads
    networks:
      - disparador_network
    environment:
      ## Dados de acesso
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=admin
      - AUTH_SECRET_KEY=a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8

      ## Banco de dados PostgreSQL
      - DATABASE_URL=postgresql://disparador_user:disparador_pass_2025@postgres:5432/disparador_db?sslmode=disable
      
      ## Preenchimento automatico
      - NEXT_PUBLIC_AUTO_FILL_DDI=true
      - NEXT_PUBLIC_DEFAULT_LOCATION=BR

      ## Dados da Evolution API
      - NEXT_PUBLIC_EVOLUTION_URL=http://localhost:8084
      - NEXT_PUBLIC_EVOLUTION_API=plataformaraphael2025

      ## Dados do Chatwoot
      - NEXT_PUBLIC_CHATWOOT_INTEGRATION=false
      - NEXT_PUBLIC_CHATWOOT_DOMAIN=
      - NEXT_PUBLIC_CHATWOOT_ACCOUNT_ID=
      - NEXT_PUBLIC_CHATWOOT_TOKEN=
      - NEXT_PUBLIC_CHATWOOT_DATABASE_CONNECTION_URI=

      ## Modo
      - NODE_ENV=production

volumes:
  disparador_data:
    driver: local
  postgres_data:
    driver: local

networks:
  disparador_network:
    driver: bridge